pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt install xmlstarlet
    cd build
    bash build.sh
  displayName: 'Building APKs'

- script: bash tests/tests.sh
  displayName: 'Running test scripts'
